### ISSUE TITLE
試走会のコース画像で6色変換の検証

### ISSUE THREAD

**Issue by kawanoichi** [KatLab-MiyazakiUniv/etrobocon2022-camera-system#18]
## 完了条件
試走会のコース画像で6色変換を行い、できているか検証を行う。
## 実現方法
６色変換を行う。

**Comment by kawanoichi** [comment]
画像を６色変換を行ったところ認識できていない色があることが分かりました。
まだ原因はわかっていません。
画像はzipで貼ってます。

# コース画像
[course_images.zip](https://github.com/KatLab-MiyazakiUniv/etrobocon2022-camera-system/files/9240513/course_images.zip)


# 結果1(パラメータ調整なし)
![スクリーンショット (211)](https://user-images.githubusercontent.com/96767490/182331987-fca54493-0a4f-4f90-9ec2-79c40dac40ff.png)

[results1.zip](https://github.com/KatLab-MiyazakiUniv/etrobocon2022-camera-system/files/9240555/results1.zip)


# 結果2 (認識でない場所だけを抽出)
![スクリーンショット (212)](https://user-images.githubusercontent.com/96767490/182331997-4d494a1f-84e8-48bf-9f94-505c9a37df91.png)

[results2.zip](https://github.com/KatLab-MiyazakiUniv/etrobocon2022-camera-system/files/9240557/results2.zip)
__UPPERの179は255でも結果は同じでした。

**Comment by mutotaka0426** [comment]
認識できていないっていうのは，うまく変換できていないって話？
それとも，6色のどれにも該当していないのがあるってこと？

results1とresults2をぱっと見た感じ，黒くなってるところが認識できていない場所？っぽいけど，これは黒って判定しているわけじゃないの？

**Comment by kodama0720** [comment]
color_changer.py 59行目でHSVが[0,0,0]の部分を置換していないから？
