### ISSUE TITLE
回頭時間の測定＆コスト設定

### ISSUE THREAD

**Issue by kodama0720** [KatLab-MiyazakiUniv/etrobocon2022-camera-system#33]
## 完了条件
- 回頭時間を計測している(45,90,135,180,225,270,315度の7パターン)
- 回頭のコストを設定している

## 実現方法
- 回頭前と回頭後の時間差から回頭時間を計測する

**Comment by mutotaka0426** [comment]
ゲーム動作を生成する時に指定する角度は45度単位の7つだろうけど，実際に回頭するときは少し値変わるみたいだから，それの対応リストみたいなのをGameMotionとかに作ってね
それでコマンドをセットするときの値をリストから持ってくればいいかな
どんなリストにするかは任せるけど，辞書型とかにすればいいかな？

45度が指定されたら，セットするコマンドは`RT,43,100,clockwise`みたいな感じになるように
