### ISSUE TITLE
運搬動作を決定する

### ISSUE THREAD

**Issue by miyashita64** [KatLab-MiyazakiUniv/etrobocon2022-camera-system#44]
## 完了条件
全ブロックの運搬動作(取得動作＋設置動作)を決定できる

## 実現方法
- 指定されたブロックの取得と設置について、最適動作探索を呼び出す運搬動作決定クラスを追加する
- 全ブロックのについて運搬動作決定を呼び出す処理を追加する

**Comment by mutotaka0426** [comment]
> あるブロックの運搬動作(取得動作＋設置動作)を決定できる

すべてのブロックではなくて？経路計画はまた別のチケットにする？モデル的には分けてたけど，纏めちゃダメかな
運搬ブロック決定と最適動作探索を組み合わせたやつを作るのがこのチケットでもいいと思うけど
